### ISSUE TITLE
[CLI][unpkg]: libman install jquery -p unpkg fails 

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/LibraryManager#157]
### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  
run `libman install jquery -p unpkg -d lib/unpkg/jquery` 

### Expected result
*What would you expect to happen if there wasn't a bug*  
jquery with the latest version is installed. 

### Actual result
*What is actually happening*  
Installation fails with the error: 
```
libman install jquery -p unpkg -d lib/unpkg/jquery
Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "http://unpkg.com/jquery@/AUTHORS.txt"
   at Microsoft.Web.LibraryManager.WebRequestHandler.GetStreamAsync(String url, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\CacheService\WebRequestHandler.cs:line 35
   at Microsoft.Web.LibraryManager.CacheService.DownloadToFileAsync(String url, String fileName, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\CacheService\CacheService.cs:line 62
   at Microsoft.Web.LibraryManager.CacheService.RefreshCacheAsync(IEnumerable`1 librariesCacheMetadata, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\CacheService\CacheService.cs:line 97
   at Microsoft.Web.LibraryManager.Providers.Unpkg.UnpkgProvider.RefreshCacheAsync(ILibraryInstallationState state, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\Providers\Unpkg\UnpkgProvider.cs:line 117
Failed to install library "jquery"
[LIB010]: Failed to download resource from "http://unpkg.com/jquery@/AUTHORS.txt"
```

**Comment by prafullbhosale** [comment]
However, `libman install @angular/cli -p unpkg -d lib/unpkg/angular` works. 

Related #156

**Comment by justcla** [comment]
After the validation updates, the error is now:<br>
```
The "1.5.1" library could not be resolved by the "unpkg" provider
```
