### ISSUE TITLE
RestoreOnBuild: Null ref exception when building 

### ISSUE THREAD

**Issue by raquelsa** [aspnet/LibraryManager#250]
1. Create a project and add a libman.json file
2. Enable Resore on build
3. Edit the libman.json to have
{
"version": "1.0",
"defaultProvider": "unpkg",
"libraries": [
  {
    "library": "d3@2.1.3",
    "destination": "Pages/d3"
  }
]
}
4. Build the project

Result:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "Microsoft.Web.LibraryManager.Build.RestoreTask" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.LibraryManager.Build.RestoreTask.PopulateFilesWritten(IEnumerable`1 results, IHostInteraction hostInteraction)
   at Microsoft.Web.LibraryManager.Build.RestoreTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	WebApplication9	C:\Users\raquela\.nuget\packages\microsoft.web.librarymanager.build\1.0.105-gb36e6bc332\build\Microsoft.Web.LibraryManager.Build.targets	35

**Comment by raquelsa** [comment]
Can not repro
