### ISSUE TITLE
Libman restore does not working

### ISSUE THREAD

**Issue by danroth27** [aspnet/LibraryManager#368]
_From @kant2002 on September 5, 2018 8:39_

If add libman.json to the project, then on new PC on the build files does not restored

_Copied from original issue: aspnet/Blazor#1389_

**Comment by johnallers** [comment]
I ran into a similar issue. Started using Libman with an existing ASP.NET Core project by using "Manage Client-Side Libraries..." in Visual Studio.

As I added libraries to the libman.json, the resources would restore properly. As soon as I tried to do a clean build, they did not. 

Adding the Microsoft.Web.LibraryManager.Build NuGet package manually to the project resolved this issue for me.

**Comment by justcla** [comment]
One option: When a user adds library files via the UI, or when a user activates "Manage Client-side Libraries", Visual Studio could prompt to Enable Restore on Build, which, if the user accepts, would add the LibMan Build NuGet package to the project.

**Comment by jimmylewis** [comment]
@justcla restore on build is not the primary scenario we designed for.  The default behavior is that a user uses LibMan to download the files into their repo (and periodically to update them), but the files are checked in by default.  This is based on the way that many users *who are not already using a package manager* consume other libraries.

One could argue that we should be pushing them to use restore on build, but the same argument could easily be adjusted to saying that we should be pushing them to using a package manager.  LibMan is primarily aiming to bridge the gap for users who do not want a package manager.

**Comment by jimmylewis** [comment]
To be clear, I'm not saying that LibMan should not support this scenario.  My concern is mostly about how complicated we make it to get started (by forcing decisions to users when they create the file) and pushing more advanced concepts too aggressively.

Managing package restore with LibMan can be tricky, especially since we support placing files, well, anywhere.  If you're going to avoid committing the fetched files, then you need to manage your .gitignore settings as well.  That's not something on our radar.

**Comment by iamkabirmalik** [comment]
Same problem here. An internal exception is thrown when restoring using the LibMan CLI tool. 

`Restoring library bootstrap@4.4.1...
System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown.
   at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)
   at System.Net.Security.SslStreamPal.DecryptMessage(SafeDeleteContext securityContext, Byte[] buffer, Int32& offset, Int32& count)
   at System.Net.Security.SecureChannel.Decrypt(Byte[] payload, Int32& offset, Int32& count)
   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)

Failed to restore "{bootstrap@4.4.1, unpkg, wwwroot/lib/bootstrap/}"
  - [LIB000]: An unknown exception occurred`

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?

**Comment by pabrams** [comment]
Wait a second... I am using a package manager:  nuget.  Are you saying I shouldn't be using libman, in that case?  Then how do I restore these libraries using nuget?
