### ISSUE TITLE
LIB010 Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.41/sounds/rm.wav"

### ISSUE THREAD

**Issue by fsmirne** [aspnet/LibraryManager#377]
I'm getting this error while trying to restore elfinder using LibMan.
Here's are the 2 errors I'm getting as well as the stack trace:

Error	LIB010	Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.41/sounds/rm.wav"

Error		Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.41/sounds/rm.wav"
   at Microsoft.Web.LibraryManager.WebRequestHandler.<GetStreamAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.CacheService.<DownloadToFileAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.CacheService.<RefreshCacheAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.LibraryManager.Providers.Cdnjs.CdnjsProvider.<RefreshCacheAsync>d__26.MoveNext()

**Comment by jodavis** [comment]
That target URL returns "403 Forbidden", so LibMan wouldn't be able to download it. The CDN might be configured to refuse download of .wav files.

We should have a clearer error message when something like this happens.

**Comment by Kizmar** [comment]
I've gotten the `Failed to download resource from "https://cdnjs.cloudflare.com` error message with every package I've tried to install using this. Everything is returning a 403.

**Comment by jimmylewis** [comment]
Has this been an issue on recent versions of LibMan (in VS2019 or with the latest CLI/build NuGet packages)?  I saw this a few times in the past with CDNJS returning HTTP403 occasionally.  It should be significantly mitigated by the retry loop added a few months ago when downloading resources, so I just wanted to check if we can close this.
