### ISSUE TITLE
Publishing .Net Core 2.2 app broken after upgrading to VS2019 16.3.1

### ISSUE THREAD

**Issue by euang** [aspnet/LibraryManager#523]
After upgrading to VS2019 16.3.1, I can no longer publish my .Net Core 2.2 app.
I'm using 2.0.76

It throws the following error:
```
Restore operation started...
C:\Users\euan\.nuget\packages\microsoft.web.librarymanager.build\2.0.76\build\Microsoft.Web.LibraryManager.Build.targets(35,9): Error MSB4018: The "Microsoft.Web.LibraryManager.Build.RestoreTask" task failed unexpectedly.
System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Web.LibraryManager.Build.Dependencies.<>c__DisplayClass10_0.<GetProvidersFromReflection>b__1(TypeInfo fac)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.Web.LibraryManager.Build.Dependencies.GetProvidersFromReflection()
   at Microsoft.Web.LibraryManager.Build.Dependencies.Initialize()
   at Microsoft.Web.LibraryManager.Build.Dependencies..ctor(IHostInteraction hostInteraction, IEnumerable`1 assemblyPaths)
   at Microsoft.Web.LibraryManager.Build.RestoreTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by jimmylewis** [comment]
This should be fixed with the 2.0.96 version.  Can you upgrade your package and give it a try?

**Comment by smabuk** [comment]
Upgrading to 2.0.96 fixed the problem for me.

**Comment by jimmylewis** [comment]
Great, thanks for confirming!
