### ISSUE TITLE
Restoring Client Side Packages Crashes Visual Studio

### ISSUE THREAD

**Issue by rhavlick** [aspnet/LibraryManager#89]
Hello, I have VS 15.7.2 and I downloaded the source code for Library Manager and created the VISX file and installed Library Manager.

When I click "Restore Client Side Packages", VS crashes.  The following errors appear in Event Viewer:

**Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.IO.Path.Combine(System.String, System.String)
   at Microsoft.Web.LibraryManager.Vsix.VsHelpers.ProjectContainsManifestFile(EnvDTE.Project)
   at Microsoft.Web.LibraryManager.Vsix.RestoreSolutionCommand+<ExecuteAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)**

Any ideas on how to fix this?

Thanks

**Comment by jimmylewis** [comment]
@raquelsa is this one addressed by #85 or is this a new issue?

**Comment by rhavlick** [comment]
Thanks Jimmy, it seems close but it may be a different issue.  I pulled this 2 days ago so I believe #85 was already committed.

What can I do to help debug this?

Thanks

**Comment by jodavis** [comment]
I think we might have some Windows Error Reporting hits on this as well.

**Comment by bhsubra** [comment]
From the call stack it looks like its the same as https://github.com/aspnet/LibraryManager/issues/256 and was fixed via commit https://github.com/aspnet/LibraryManager/commit/80110aacb958b20d625daacf66a1b4fbb45c9cdf.

@rhavlick , I'll go ahead and close this. The fix should be available in 15.8 Preview 5.

Thanks!
